<#assign chart_figcaption_map = {
	"redundancy"            : "Verteilung der Redundanzanteile",
	"p_prio"                : "Verteilung der &Uuml;berschreitungswahrscheinlichkeit",
	"influence_on_position" : "Verteilung des Einflusses einer unentdecken Modellst&ouml;rung auf die Punktlage"
}>

<#assign mean_interval = "Mittleres Intervall">
<#assign plot_svg_support = "Ihr Browser kann keine skalierbaren Vektorgrafiken (SVG) darstellen.">