<#assign chart_figcaption_map = {
	"redundancy"            : "Distribution of redundancy",
	"p_prio"                : "Distribution of (a-priori) probability value",
	"influence_on_position" : "Distribution of influence on point position due to an undetected gross-error"
}>

<#assign mean_interval = "Mean interval">
<#assign plot_svg_support = "Scalable Vector Graphics (SVG) are unsupported by your browser.">