<#assign point_table_header_map = {
		"id"   : "Punktnummer",
		"code" : "Code",

		"y" :    "Rechts y",
		"x" :    "Hoch x",
		"z" :    "H&ouml;he z"	
}>

<#assign point_type_map = {
		"reference_point"  :    "Festpunkte",
		"stochastic_point" :    "Anschlu&szlig;punkte",
		"datum_point"      :    "Datumspunkte",
		"new_point"        :    "Neupunkte"
}>

<#assign point_table_caption = "Punktgruppe">