<#assign point_table_header_map = {
		"id" :   "Punktnummer",
		"code" : "Code",

		"y" :    "Rechts Y",
		"x" :    "Hoch X",
		"z" :    "H&ouml;he Z"	
}>

<#assign point_type_map = {
		"reference_point"  :    "Festpunkte",
		"stochastic_point" :    "Anschlu&szlig;punkte",
		"datum_point"      :    "Datumspunkte",
		"new_point"        :    "Neupunkte"
}>

<#assign point_table_caption = "Punktgruppe">