<#assign vertical_deflection_table_header_map = {
		"id"   : "Point-Id"
}>

<#assign vertical_deflection_type_map = {
		"reference_vertical_deflection"  :  "Reference Deflection of the Vertical",
		"stochastic_vertical_deflection" :  "Stochastic Deflection of the Vertical",
		"unknown_vertical_deflection"    :  "Unknown Deflection of the Vertical"
}>

<#assign vertical_deflection_table_caption = "Deflection of the Vertical">