<#assign vertical_deflection_table_header_map = {
		"id"   : "Punktnummer"
}>

<#assign vertical_deflection_type_map = {
		"reference_vertical_deflection"  :  "Varianzfreie Lotabweichungen",
		"stochastic_vertical_deflection" :  "Stochastische Lotabweichungen",
		"unknown_vertical_deflection"    :  "Gesch&auml;tzte Lotabweichungen"
}>

<#assign vertical_deflection_table_caption = "Lotabweichungen">