package org.applied_geodesy.jag3d.ui.table;

public enum ColumnType {
	APRIORI_TERRESTRIAL_OBSERVATION,
	APOSTERIORI_TERRESTRIAL_OBSERVATION,
	
	APRIORI_GNSS_OBSERVATION,
	APOSTERIORI_GNSS_OBSERVATION,
	
	APRIORI_POINT,
	APOSTERIORI_POINT,
	
	APRIORI_DEFLECTION,
	APOSTERIORI_DEFLECTION,
	
	APRIORI_POINT_CONGRUENCE,
	APOSTERIORI_POINT_CONGRUENCE,
	APOSTERIORI_DEFLECTION_CONGRUENCE,
	
	VISIBLE,
	HIDDEN
	;
}
