package org.applied_geodesy.jag3d.ui.menu;

enum MenuItemType {
	NEW, 
	OPEN,
	PREFERENCES,
	TEST_STATISTIC,
	HORIZONTAL_PROJECTION,
	CONGRUENT_POINT,
	RANK_DEFECT,
	AVERAGE,
	APROXIMATE_VALUES,
	LEAST_SQUARES,
	EXIT,
	
	ABOUT,
	
	IMPORT_FLAT_LEVELLING, 
	IMPORT_FLAT_DIRECTION, 
	IMPORT_FLAT_HORIZONTAL_DISTANCE, 
	IMPORT_FLAT_SLOPE_DISTANCE, 
	IMPORT_FLAT_ZENITH_ANGLE, 
	IMPORT_FLAT_GNSS1D, 
	IMPORT_FLAT_GNSS2D, 
	IMPORT_FLAT_GNSS3D,
	
	IMPORT_BEO,
	IMPORT_Z,
	IMPORT_DL100,
	
	IMPORT_M5,
	
	IMPORT_GSI1D,
	IMPORT_GSI2D,
	IMPORT_GSI2DH,
	IMPORT_GSI3D,
	
	IMPORT_LAND_XML2D,
	IMPORT_LAND_XML3D,
	
	IMPORT_JOB_XML2D,
	IMPORT_JOB_XML2DH,
	IMPORT_JOB_XML3D,

}
