package org.applied_geodesy.jag3d.ui.tabpane;

public enum TabType {
	META_DATA,
	GRAPHIC,
	RAW_DATA,
	RESULT_DATA,
	RESULT_CONGRUENCE_ANALYSIS_POINT,
	RESULT_CONGRUENCE_ANALYSIS_DEFLECTION,
	RESULT_DEFLECTION,
	ADDITIONAL_PARAMETER,
	PROPERTIES
	;
}
