<thead>
	<tr>
		<th><#outputformat "plainText">${euler_angles_table_header_map['convention']}</#outputformat></th>
		<th><#outputformat "plainText">&phi;<span class="unit">${unit_abbr_angle}</span></#outputformat></th>
		<th><#outputformat "plainText">&theta;<span class="unit">${unit_abbr_angle}</span></#outputformat></th>
		<th><#outputformat "plainText">&psi;<span class="unit">${unit_abbr_angle}</span></#outputformat></th>
	</tr>
</thead>