<thead>
	<tr>
		<th><#outputformat "plainText">${principal_component_header_map['index']}</#outputformat></th>
		<th><#outputformat "plainText">${principal_component_header_map['value']}<span class="unit">${unit_abbr_length_residual}</span></#outputformat></th>
		<th><#outputformat "plainText">${principal_component_header_map['ratio']}<span class="unit">${unit_abbr_percentage}</span></#outputformat></th>
	</tr>
</thead>