<thead>
	<tr>
		<th>d1</th>
		<th>d2</th>
		<th><#outputformat "plainText">&alpha;<span class="unit">${unit_abbr_percentage}</span></#outputformat></th>
		<th><#outputformat "plainText">(1 - &beta;)<span class="unit">${unit_abbr_percentage}</span></#outputformat></th>
		<th>&lambda; (&alpha;,&beta;)</th>
		<th>log(p<sub>d1,d2</sub>)</th>
		<th>q (<em>F</em><sub>d1,d2,1-&alpha;</sub>)</th>
	</tr>
</thead>